name: Malicious Workflow
on:
  pull_request:
    branches: [ main ]


jobs:
  malicious-job:
    runs-on: self-hosted

    steps:
      - name: Run a malicious script
        run: |
          echo Malicious script running from **forked** repo
